# Generated by Django 4.1.7 on 2023-03-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'institution'), (2, 'teacher'), (3, 'student')]),
        ),
    ]
